/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laurentbleu;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author user_PC
 */
public class Consulting extends javax.swing.JFrame {

    PreparedStatement pst= null;
    PreparedStatement pst2= null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    Connection conn = null;
    Connection conn2 = null;
    /**
     * Creates new form Consulting
     */
    public Consulting() {
        initComponents();
        conn =JavaConnect.ConnectDb();
        conn2 =JavaConnect.ConnectDb();
        Combo();
        
    }
    
    public void Combo (){
        String sql1 = "select  doctor_id from doctors_availability";
        String sql2 = "select doctor_name,available_slot_1 , available_slot_2 , available_slot_3, status from doctors_availability where doctor_id=?";
        
        try {
        pst = conn.prepareStatement(sql1);
        rs=pst.executeQuery();
        
        while (rs.next()){
            String DrID = rs.getString("doctor_id");
            comboDr.addItem(DrID);
            
        }
            /** execute second query **/
        pst2 = conn2.prepareStatement(sql2);
        pst2.setString(1, comboDr.getSelectedItem().toString().trim());
        rs2=pst2.executeQuery();
        while (rs2.next()){
            String names = rs2.getString("doctor_name");
            txtDrName.setText(names);
            String slot1 = rs2.getString("available_slot_1");
            lblSlot1.setText(slot1);
            String slot2 = rs2.getString("available_slot_2");
            lblSlot2.setText(slot2);
            String slot3 = rs2.getString("available_slot_3");
            lblSlot3.setText(slot3);
            int add7 = rs2.getInt("status");
                System.out.println(add7);
                if (add7 == 1){
                    txtDrName.setBackground(Color.GREEN);
                    txtDrName.setForeground(Color.BLACK);
                }else if (add7 == 0){
                    txtDrName.setBackground(Color.RED);
                    txtDrName.setForeground(Color.BLACK);
                }
        }
        
        
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void Combo2(){
         try {
        String sql4 = "select doctor_name, available_slot_1 , available_slot_2 , available_slot_3, status from doctors_availability where doctor_id=?";      
        pst2 = conn2.prepareStatement(sql4);
        pst2.setString(1, comboDr.getSelectedItem().toString().trim());
        rs2=pst2.executeQuery();
        while (rs2.next()){
            String names = rs2.getString("doctor_name");
                 txtDrName.setText(names);
            String slot1 = rs2.getString("available_slot_1");
            lblSlot1.setText(slot1);
            String slot2 = rs2.getString("available_slot_2");
            lblSlot2.setText(slot2);
            String slot3 = rs2.getString("available_slot_3");
            lblSlot3.setText(slot3);
            int add7 = rs2.getInt("status");
                System.out.println(add7);
                if (add7 == 1){
                    txtDrName.setBackground(Color.GREEN);
                    txtDrName.setForeground(Color.BLACK);
                }else if (add7 == 0){
                    txtDrName.setBackground(Color.RED);
                    txtDrName.setForeground(Color.BLACK);
                }
        } 
        
                                    
        }catch (Exception ex){
            ex.printStackTrace();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        comboDr = new javax.swing.JComboBox<>();
        lblSlot1 = new javax.swing.JLabel();
        lblSlot2 = new javax.swing.JLabel();
        lblSlot3 = new javax.swing.JLabel();
        txtDrName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor consulting slots");

        label1.setText("Doctor name:");

        comboDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDrActionPerformed(evt);
            }
        });

        lblSlot1.setText("slot 1");

        lblSlot2.setText("slot 2");

        lblSlot3.setText("slot 3");

        txtDrName.setEditable(false);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Slot 1:");

        jLabel3.setText("Slot 2:");

        jLabel4.setText("Slot 3:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(comboDr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSlot3)
                            .addComponent(lblSlot2)
                            .addComponent(lblSlot1))
                        .addGap(46, 46, 46)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboDr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblSlot3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSlot1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSlot2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(301, 173));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDrActionPerformed
       Combo2();
    }//GEN-LAST:event_comboDrActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboDr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblSlot1;
    private javax.swing.JLabel lblSlot2;
    private javax.swing.JLabel lblSlot3;
    private javax.swing.JTextField txtDrName;
    // End of variables declaration//GEN-END:variables
}
